//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoCatalogue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoCatalogue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string category_other {
            get {
                return ResourceManager.GetString("category_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivated?.
        /// </summary>
        public static string deactivated_check {
            get {
                return ResourceManager.GetString("deactivated_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install voicebank.
        /// </summary>
        public static string install_button {
            get {
                return ResourceManager.GetString("install_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each character belongs to their respective IP holder..
        /// </summary>
        public static string ip_disclaimer {
            get {
                return ResourceManager.GetString("ip_disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add voicebanks.
        /// </summary>
        public static string tooltip_addvbs {
            get {
                return ResourceManager.GetString("tooltip_addvbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tooltip_settings {
            get {
                return ResourceManager.GetString("tooltip_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voicebank website.
        /// </summary>
        public static string tooltip_vbwebsite {
            get {
                return ResourceManager.GetString("tooltip_vbwebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string vocalist_activationcode {
            get {
                return ResourceManager.GetString("vocalist_activationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data registry.
        /// </summary>
        public static string vocalist_dr {
            get {
                return ResourceManager.GetString("vocalist_dr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Voicebank first!.
        /// </summary>
        public static string vocalist_dr_ac_help {
            get {
                return ResourceManager.GetString("vocalist_dr_ac_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string vocalist_dr_apply {
            get {
                return ResourceManager.GetString("vocalist_dr_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string vocalist_dr_clear {
            get {
                return ResourceManager.GetString("vocalist_dr_clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local PC address of the installer.
        /// </summary>
        public static string vocalist_dr_il_help {
            get {
                return ResourceManager.GetString("vocalist_dr_il_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string vocalist_dr_update {
            get {
                return ResourceManager.GetString("vocalist_dr_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installer Location.
        /// </summary>
        public static string vocalist_installocation {
            get {
                return ResourceManager.GetString("vocalist_installocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string vocalist_name {
            get {
                return ResourceManager.GetString("vocalist_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add your voicebanks in this screen. Empty activation codes will be considered as &apos;&apos;not owned&apos;&apos;..
        /// </summary>
        public static string vocalist_tutorial {
            get {
                return ResourceManager.GetString("vocalist_tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string vocasettings_about {
            get {
                return ResourceManager.GetString("vocasettings_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate profile images.
        /// </summary>
        public static string vocasettings_g_alts {
            get {
                return ResourceManager.GetString("vocasettings_g_alts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable automatic activation code copy to Clipboard.
        /// </summary>
        public static string vocasettings_g_disablecopy {
            get {
                return ResourceManager.GetString("vocasettings_g_disablecopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid format:.
        /// </summary>
        public static string vocasettings_g_grid {
            get {
                return ResourceManager.GetString("vocasettings_g_grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        public static string vocasettings_g_language {
            get {
                return ResourceManager.GetString("vocasettings_g_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all data.
        /// </summary>
        public static string vocasettings_g_reset {
            get {
                return ResourceManager.GetString("vocasettings_g_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any changes require restarting VoCatalogue to be applied..
        /// </summary>
        public static string vocasettings_g_warning {
            get {
                return ResourceManager.GetString("vocasettings_g_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string vocasettings_general {
            get {
                return ResourceManager.GetString("vocasettings_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set DeepVocal folder.
        /// </summary>
        public static string vocasettings_s_deepvocal {
            get {
                return ResourceManager.GetString("vocasettings_s_deepvocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free SDK engines.
        /// </summary>
        public static string vocasettings_s_freesdk {
            get {
                return ResourceManager.GetString("vocasettings_s_freesdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool location:.
        /// </summary>
        public static string vocasettings_s_tool {
            get {
                return ResourceManager.GetString("vocasettings_s_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vocasettings_s_utau {
            get {
                return ResourceManager.GetString("vocasettings_s_utau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vocasettings_s_v2import {
            get {
                return ResourceManager.GetString("vocasettings_s_v2import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vocasettings_s_v4activate {
            get {
                return ResourceManager.GetString("vocasettings_s_v4activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string vocasettings_specific {
            get {
                return ResourceManager.GetString("vocasettings_specific", resourceCulture);
            }
        }
    }
}
